// mocked data

import { Company, Interview, JobApplication, Offer } from "@prisma/client";

export const offerData: Offer = {
  id: "1",
  position: "Software Engineer",
  jobDescription: "Software Engineer at Google",
  benefits: ["Health Insurance", "401k"],
  salary: 100000,
  offerDate: new Date(),
  createdAt: new Date(),
  updatedAt: new Date(),
};

export const companyData: Company[] = [
  {
    id: "1",
    name: "Google",
    contactPerson: "John Doe",
    industry: "Tech",
    location: "Mountain View, CA",
    website: "https://google.com",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    name: "Facebook",
    contactPerson: "Jane Doe",
    industry: "Tech",
    location: "Menlo Park, CA",
    website: "https://facebook.com",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    name: "Microsoft",
    contactPerson: "Bill Gates",
    industry: "Tech",
    location: "Cupertino, CA",
    website: "https://apple.com",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const jobApplicationData: JobApplication[] = [
  {
    id: "1",
    position: "Software Engineer",
    status: "Offer",
    dateApplied: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1",
    companyId: "1",
    offerId: "1",
  },
  {
    id: "2",
    position: "QA Tester",
    status: "Applied",
    dateApplied: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1",
    companyId: "2",
    offerId: "1",
  },
  {
    id: "3",
    position: "Product Manager",
    status: "Applied",
    dateApplied: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1",
    companyId: "1",
    offerId: "1",
  },
  {
    id: "4",
    position: "Project Manager",
    status: "Applied",
    dateApplied: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
    userId: "1",
    companyId: "3",
    offerId: "1",
  },
];

export const interviewData: Interview[] = [
  {
    id: "1",
    applicationId: "1",
    interviewDate: new Date("2024-06-01 08:00:00"),
    interviewer: "Jane Doe",
    interviewType: "Technical",
    feedback: "Great interview",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    applicationId: "2",
    interviewDate: new Date("2024-06-02 08:00:00"),
    interviewer: "John Doe",
    interviewType: "Technical",
    feedback: "Great interview",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    applicationId: "3",
    interviewDate: new Date("2024-06-03 08:00:00"),
    interviewer: "Jane Doe",
    interviewType: "Technical",
    feedback: "Great interview",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    applicationId: "4",
    interviewDate: new Date("2024-06-04 08:00:00"),
    interviewer: "John Doe",
    interviewType: "Technical",
    feedback: "Great interview",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
